### ISSUE TITLE
Remove auto display of featured images from posts (Komin/Nyheter)

### ISSUE THREAD

**Issue by hillsidepeak** [malmostad/wp-apps#14]
Editors should be able to choose if they want to show or not to show an image in a post.
Therefore we have decided to remove the auto display of the featured image from posts in Komin/Nyheter. If the editor still wants to show an image, they now have to add one to the post with the original "Add media" function.
The featured image function itself should still be used, but only to display images in the news feed.

**Comment by martent** [comment]
Out in test:

https://webapps04.malmo.se/nyheter-test

Please verify.

**Comment by martent** [comment]
I made a deploy in production as well at the same time as the WP upgrade.

**Comment by hillsidepeak** [comment]
Changes works as intended.
