### ISSUE TITLE
WP sends out wrong emails

### ISSUE THREAD

**Issue by jesperbylund** [malmostad/wp-apps#15]
Users, a few ever day, get the following message.
![fullsizerender](https://cloud.githubusercontent.com/assets/3509721/13425491/64cd35f2-dfa7-11e5-81a2-be4425ddfb0d.jpeg)

**Comment by elilun14** [comment]
Gäller det första ärendet personer som har publicerarbehörighet i WP, eller skickas sådant här till slumpmässiga bland alla 25 000 slutavändare?
#69 är menat för alla 25000 där någon kommenterat i en nyhet eller blogg, och där identiteten (=epostadressen) bör kunna hämtas från folks inloggning?

**Comment by elilun14** [comment]
Ett antal mail i webbteamets funktionsbrevlåda, från förvirrade publicerare, verkar handla om detta.

**Comment by martent** [comment]
Jag har installerat ett tillägg, "Manage Notification E-mails", för Komin-nyheter och Komin-blogg. Man anger vad som ska trigga notificationsmeddelanden under Inställningar, Notification e-mails. Jag har kryssat ur valet "E-mail address change notification to user" vilket ska hindra att e-post skickas till vissa medarbetaren vid inloggning.

Jag har även kryssat ur alla andra notifikationer förutom "Notify post author" som får e-postnotifikation när någon kommenterar.

Detta tillägg löser tyvärr inte behovet att prenumerera på kommentarer för inlägg där man själv har kommenterat, https://github.com/malmostad/intranet-dashboard/issues/69

cc: @perber14, @Svempan

**Comment by perber14** [comment]
Mycket bra! Det kommer ju förvånade (upprördshetsgrad varierar) mejl om detta flera gånger i veckan. Skönt om det kan undvikas framåt.

**Comment by magnivar** [comment]
Inga arga mail kommer så det verkar löst.
