### ISSUE TITLE
Datum för avpublicering av nyheter

### ISSUE THREAD

**Issue by olajoh1** [malmostad/wp-apps#17]
Datum för avpublicering ska göras obligatoriskt vid publicering av nyheter.

**Comment by magnivar** [comment]
Längsta tid för att leva är 4 månader.

**Comment by magnivar** [comment]
Hitta någon plug-in i WP? Eller flytta Nyheter till SV?

**Comment by elilun14** [comment]
Fyra månader gamla nyheter rensas manuellt idag. Eftersom vi lär lämna wordpress på sikt tycker jag vi låter det vara som idag, och inte lägger resurser på en plug-in.
